
# This workflow creates a branch from the translations/fr folder
env:
  # **CHANGE THIS** for other languages
  LANG_CODE: fr

name: French [FR] Translations

# Runs on push to master, only when files under `docs/fr` are modified
on:
  push:
    branches: [ master ]
    paths:
      # **CHANGE THIS** for other languages
      - 'translations/fr/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Create branch from translations/fr folder
    - name: Create branch from language
      run: |
        git config --global user.email "developer@digital-democracy.org"
        git config --global user.name "Dd Github Bot"
        ./scripts/create-translated-branch.sh $LANG_CODE
        git push -f origin translations-$LANG_CODE:translations-$LANG_CODE
